version: 1
disable_existing_loggers: false

formatters:
  json:
    (): lab.core.logging.JSONFormatter
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: ${LOG_FILE}
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  null:
    class: logging.NullHandler

loggers:
  lab:
    level: DEBUG
    handlers: [file]
    propagate: false

  # Third party loggers
  urllib3:
    level: WARNING
    handlers: [null]
    propagate: false
  
  asyncio:
    level: WARNING
    handlers: [null]
    propagate: false

root:
  level: WARNING
  handlers: [file]
